appenders:
  std_out:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  file_logger:
    kind: rolling_file
    path: "log/pot_bot.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50kb
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "log/pot_bot.log.{}"
root:
  level: error
  appenders:
    - std_out
    - file_logger

loggers:
  dev:
    level: debug
    appenders:
      - std_out
      - file_logger
    additive: false
